// <auto-generated/>
#pragma warning disable CS0618
using EndOfLifeDate.Client.Products.Item.Releases.Item;
using EndOfLifeDate.Client.Products.Item.Releases.Latest;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace EndOfLifeDate.Client.Products.Item.Releases
{
    /// <summary>
    /// Builds and executes requests for operations under \products\{product}\releases
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ReleasesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The latest property</summary>
        public global::EndOfLifeDate.Client.Products.Item.Releases.Latest.LatestRequestBuilder Latest
        {
            get => new global::EndOfLifeDate.Client.Products.Item.Releases.Latest.LatestRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the EndOfLifeDate.Client.products.item.releases.item collection</summary>
        /// <param name="position">A release cycle name.</param>
        /// <returns>A <see cref="global::EndOfLifeDate.Client.Products.Item.Releases.Item.WithReleaseItemRequestBuilder"/></returns>
        public global::EndOfLifeDate.Client.Products.Item.Releases.Item.WithReleaseItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("release", position);
                return new global::EndOfLifeDate.Client.Products.Item.Releases.Item.WithReleaseItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EndOfLifeDate.Client.Products.Item.Releases.ReleasesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReleasesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/products/{product}/releases", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EndOfLifeDate.Client.Products.Item.Releases.ReleasesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReleasesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/products/{product}/releases", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
