// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace EndOfLifeDate.Client.Models
{
    /// <summary>
    /// Full details of a product.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProductDetails : IParsable
    {
        /// <summary>Aliases declared for the product (derived from alternate_urls).The array is empty when no alias is declared.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Aliases { get; set; }
#nullable restore
#else
        public List<string> Aliases { get; set; }
#endif
        /// <summary>Category of the product.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Category { get; set; }
#nullable restore
#else
        public string Category { get; set; }
#endif
        /// <summary>Known identifiers (purl, repology, cpe...) associated to the product.The array is empty when no identifier is declared.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::EndOfLifeDate.Client.Models.Identifier>? Identifiers { get; set; }
#nullable restore
#else
        public List<global::EndOfLifeDate.Client.Models.Identifier> Identifiers { get; set; }
#endif
        /// <summary>Label of the product.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Label { get; set; }
#nullable restore
#else
        public string Label { get; set; }
#endif
        /// <summary>Product labels.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::EndOfLifeDate.Client.Models.ProductDetails_labels? Labels { get; set; }
#nullable restore
#else
        public global::EndOfLifeDate.Client.Models.ProductDetails_labels Labels { get; set; }
#endif
        /// <summary>Product links.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::EndOfLifeDate.Client.Models.ProductDetails_links? Links { get; set; }
#nullable restore
#else
        public global::EndOfLifeDate.Client.Models.ProductDetails_links Links { get; set; }
#endif
        /// <summary>Name of the product.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>A list of all product releases.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::EndOfLifeDate.Client.Models.ProductRelease>? Releases { get; set; }
#nullable restore
#else
        public List<global::EndOfLifeDate.Client.Models.ProductRelease> Releases { get; set; }
#endif
        /// <summary>Tags associated to the product.Given the category is also a tag, the array will always contain at least one tag.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Tags { get; set; }
#nullable restore
#else
        public List<string> Tags { get; set; }
#endif
        /// <summary>Command that can be used to check the current product version.This field is null when the command is not known.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VersionCommand { get; set; }
#nullable restore
#else
        public string VersionCommand { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::EndOfLifeDate.Client.Models.ProductDetails"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::EndOfLifeDate.Client.Models.ProductDetails CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::EndOfLifeDate.Client.Models.ProductDetails();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "aliases", n => { Aliases = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "category", n => { Category = n.GetStringValue(); } },
                { "identifiers", n => { Identifiers = n.GetCollectionOfObjectValues<global::EndOfLifeDate.Client.Models.Identifier>(global::EndOfLifeDate.Client.Models.Identifier.CreateFromDiscriminatorValue)?.AsList(); } },
                { "label", n => { Label = n.GetStringValue(); } },
                { "labels", n => { Labels = n.GetObjectValue<global::EndOfLifeDate.Client.Models.ProductDetails_labels>(global::EndOfLifeDate.Client.Models.ProductDetails_labels.CreateFromDiscriminatorValue); } },
                { "links", n => { Links = n.GetObjectValue<global::EndOfLifeDate.Client.Models.ProductDetails_links>(global::EndOfLifeDate.Client.Models.ProductDetails_links.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "releases", n => { Releases = n.GetCollectionOfObjectValues<global::EndOfLifeDate.Client.Models.ProductRelease>(global::EndOfLifeDate.Client.Models.ProductRelease.CreateFromDiscriminatorValue)?.AsList(); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "versionCommand", n => { VersionCommand = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("aliases", Aliases);
            writer.WriteStringValue("category", Category);
            writer.WriteCollectionOfObjectValues<global::EndOfLifeDate.Client.Models.Identifier>("identifiers", Identifiers);
            writer.WriteStringValue("label", Label);
            writer.WriteObjectValue<global::EndOfLifeDate.Client.Models.ProductDetails_labels>("labels", Labels);
            writer.WriteObjectValue<global::EndOfLifeDate.Client.Models.ProductDetails_links>("links", Links);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfObjectValues<global::EndOfLifeDate.Client.Models.ProductRelease>("releases", Releases);
            writer.WriteCollectionOfPrimitiveValues<string>("tags", Tags);
            writer.WriteStringValue("versionCommand", VersionCommand);
        }
    }
}
#pragma warning restore CS0618
