// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace EndOfLifeDate.Client.Models
{
    /// <summary>
    /// Product labels.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProductDetails_labels : IParsable
    {
        /// <summary>Label used to denote the discontinuation of the product.This field is mainly used for hardware, it is always null for software.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Discontinued { get; set; }
#nullable restore
#else
        public string Discontinued { get; set; }
#endif
        /// <summary>Label used to denote the phase before the end of active support of the product.This field is null when the product does not have an active support phase.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Eoas { get; set; }
#nullable restore
#else
        public string Eoas { get; set; }
#endif
        /// <summary>Label used to denote the phase before the end of extended support of the product.This field is null when the product does not have an extended support phase.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Eoes { get; set; }
#nullable restore
#else
        public string Eoes { get; set; }
#endif
        /// <summary>Label used to denote the phase before the end of life of the product.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Eol { get; set; }
#nullable restore
#else
        public string Eol { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::EndOfLifeDate.Client.Models.ProductDetails_labels"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::EndOfLifeDate.Client.Models.ProductDetails_labels CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::EndOfLifeDate.Client.Models.ProductDetails_labels();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "discontinued", n => { Discontinued = n.GetStringValue(); } },
                { "eoas", n => { Eoas = n.GetStringValue(); } },
                { "eoes", n => { Eoes = n.GetStringValue(); } },
                { "eol", n => { Eol = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("discontinued", Discontinued);
            writer.WriteStringValue("eoas", Eoas);
            writer.WriteStringValue("eoes", Eoes);
            writer.WriteStringValue("eol", Eol);
        }
    }
}
#pragma warning restore CS0618
