// <auto-generated/>
#pragma warning disable CS0618
using EndOfLifeDate.Client.Identifiers.Item;
using EndOfLifeDate.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace EndOfLifeDate.Client.Identifiers
{
    /// <summary>
    /// Builds and executes requests for operations under \identifiers
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class IdentifiersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the EndOfLifeDate.Client.identifiers.item collection</summary>
        /// <param name="position">Identifier type.</param>
        /// <returns>A <see cref="global::EndOfLifeDate.Client.Identifiers.Item.WithIdentifier_typeItemRequestBuilder"/></returns>
        public global::EndOfLifeDate.Client.Identifiers.Item.WithIdentifier_typeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("identifier_type", position);
                return new global::EndOfLifeDate.Client.Identifiers.Item.WithIdentifier_typeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EndOfLifeDate.Client.Identifiers.IdentifiersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IdentifiersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/identifiers", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EndOfLifeDate.Client.Identifiers.IdentifiersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IdentifiersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/identifiers", rawUrl)
        {
        }
        /// <summary>
        /// List all identifier types, such as a purl, known in endoflife.date.
        /// </summary>
        /// <returns>A <see cref="global::EndOfLifeDate.Client.Models.UriListResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::EndOfLifeDate.Client.Models.UriListResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::EndOfLifeDate.Client.Models.UriListResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::EndOfLifeDate.Client.Models.UriListResponse>(requestInfo, global::EndOfLifeDate.Client.Models.UriListResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List all identifier types, such as a purl, known in endoflife.date.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::EndOfLifeDate.Client.Identifiers.IdentifiersRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::EndOfLifeDate.Client.Identifiers.IdentifiersRequestBuilder WithUrl(string rawUrl)
        {
            return new global::EndOfLifeDate.Client.Identifiers.IdentifiersRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
