// <auto-generated/>
#pragma warning disable CS0618
using EndOfLifeDate.Client.Categories;
using EndOfLifeDate.Client.Identifiers;
using EndOfLifeDate.Client.Models;
using EndOfLifeDate.Client.Products;
using EndOfLifeDate.Client.Tags;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Json;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace EndOfLifeDate.Client
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EndOfLifeDateClient : BaseRequestBuilder
    {
        /// <summary>The categories property</summary>
        public global::EndOfLifeDate.Client.Categories.CategoriesRequestBuilder Categories
        {
            get => new global::EndOfLifeDate.Client.Categories.CategoriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The identifiers property</summary>
        public global::EndOfLifeDate.Client.Identifiers.IdentifiersRequestBuilder Identifiers
        {
            get => new global::EndOfLifeDate.Client.Identifiers.IdentifiersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The products property</summary>
        public global::EndOfLifeDate.Client.Products.ProductsRequestBuilder Products
        {
            get => new global::EndOfLifeDate.Client.Products.ProductsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tags property</summary>
        public global::EndOfLifeDate.Client.Tags.TagsRequestBuilder Tags
        {
            get => new global::EndOfLifeDate.Client.Tags.TagsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EndOfLifeDate.Client.EndOfLifeDateClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EndOfLifeDateClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            if (string.IsNullOrEmpty(RequestAdapter.BaseUrl))
            {
                RequestAdapter.BaseUrl = "https://endoflife.date/api/v1";
            }
            PathParameters.TryAdd("baseurl", RequestAdapter.BaseUrl);
        }
        /// <summary>
        /// List the main endoflife.date API endpoints.
        /// </summary>
        /// <returns>A <see cref="global::EndOfLifeDate.Client.Models.UriListResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::EndOfLifeDate.Client.Models.UriListResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::EndOfLifeDate.Client.Models.UriListResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::EndOfLifeDate.Client.Models.UriListResponse>(requestInfo, global::EndOfLifeDate.Client.Models.UriListResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List the main endoflife.date API endpoints.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
    }
}
#pragma warning restore CS0618
