name: Publish to GitHub Packages

on:
  # Allow manual triggering only
  workflow_dispatch:

env:
  PROJECT_PATH: 'src/Client/EndOfLifeDate.Client.csproj'

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      # Required for GitHub Packages
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore
      run: dotnet restore

    - name: Build
      run: |
        dotnet build \
          --configuration Release \
          --no-restore

    - name: Pack
      run: |
        dotnet pack \
          ${{ env.PROJECT_PATH }} \
          --configuration Release \
          --no-build \
          --output ./nupkg \
          -p:ContinuousIntegrationBuild=true \
          -p:VersionSuffix=$(date +%Y%m%d%H%M)

    - name: Authenticate to GH Packages
      run: |
        dotnet nuget add source \
          --username ${{ github.repository_owner }} \
          --password ${{ secrets.GITHUB_TOKEN }} \
          --store-password-in-clear-text \
          --name github \
          "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

    - name: Publish to GitHub Packages
      run: |
        dotnet nuget push ./nupkg/*.nupkg \
          --source github \
          --skip-duplicate

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nuget-packages
        path: ./nupkg/*.nupkg
